name: Update Issue Status
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
    mark_under_review:
      if: ${{ !github.event.pull_request.draft }}
      name: "Update Issue: Under Review"
      runs-on: ubuntu-latest
      steps:
        - name: Get Linked Issues
          id: get_linked_issues
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_ID: ${{ github.event.pull_request.node_id }}
          run: |
            echo "GH_TOKEN:"
            echo "$GH_TOKEN"
            echo "PR_ID:"
            echo "$PR_ID"
            linked_issues="$( gh api graphql -f query='
              query(
                $pr: ID!
              ) {
                node(id: $pr) {
                  ... on PullRequest {
                    closingIssuesReferences(first:5, userLinkedOnly:false) {
                      totalCount
                      nodes { 
                        id
                      }
                    }
                  }
                }
              }' -f pr=$PR_ID --jq '.data.node.closingIssuesReferences.nodes')"
            echo "ISSUE IDs:"
            echo "$linked_issues"
            echo "LINKED_ISSUE_ID=$linked_issues" >> $GITHUB_ENV
        